### ISSUE TITLE
Any plans of migrating to llvmlite?

### ISSUE THREAD

**Issue by sowani** [ContinuumIO/pykit#5]
First of all - sorry for posting it here instead of the current pykit repository. I understand the repository has moved to https://github.com/flypy/pykit however I did not find "issues" tab there.

One of pykit dependency is llvm-py which is not obsolete and has been replaced with llvmlite. Are there any plans of migrating pykit from llvm-py to llvmlite? Thanks!

**Comment by markflorisson** [comment]
Hi @sowani, this project is also horribly unmaintained :) You're really better off forking this or copying whichever parts you need.

**Comment by sowani** [comment]
Thanks @markflorisson Actually I was thinking of porting this project to ppc64le, but with the latest update I will drop this from my list.
